# Generated by Django 2.0.3 on 2019-04-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='kind_topping',
        ),
        migrations.AddField(
            model_name='topping',
            name='kind_topping',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Price'),
        ),
    ]
