# Generated by Django 2.0.3 on 2019-04-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pizza_speical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='price',
            name='num_toppings',
        ),
        migrations.RemoveField(
            model_name='price',
            name='size',
        ),
        migrations.AddField(
            model_name='price',
            name='kind_pizza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Pizza'),
            preserve_default=False,
        ),
    ]
