# Generated by Django 2.0.3 on 2019-04-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_dinnerplatters_dinnerplattersprice_pasta_salads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='PizzaPrice',
        ),
        migrations.RenameModel(
            old_name='Topping',
            new_name='PizzaTopping',
        ),
    ]
