# Generated by Django 2.0.3 on 2019-04-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190407_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaprice',
            name='pizza_kind',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Pizza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzatopping',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='toppings_pizza', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='pizzatopping',
            name='price',
            field=models.ManyToManyField(blank=True, related_name='toppings_pice', to='orders.PizzaPrice'),
        ),
    ]
