# Generated by Django 2.0.3 on 2019-04-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190407_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=64)),
                ('extracheese', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubsPrices', to='orders.Subs')),
            ],
        ),
        migrations.CreateModel(
            name='SubsSteak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
                ('addonkind', models.CharField(max_length=64)),
                ('extracheese', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubsSteakPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssPrices', to='orders.SubsSteak')),
            ],
        ),
    ]
