# Generated by Django 2.0.3 on 2019-04-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_subs_subsprice_subssteak_subssteakprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
