# Generated by Django 2.0.3 on 2019-04-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaprice',
            name='pizza_kind',
        ),
        migrations.RemoveField(
            model_name='pizzatopping',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizzatopping',
            name='price',
        ),
        migrations.DeleteModel(
            name='PizzaPrice',
        ),
        migrations.DeleteModel(
            name='PizzaTopping',
        ),
    ]
