# Generated by Django 2.0.3 on 2019-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_pizzaprice_pizzatopping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatopping',
            name='price',
            field=models.ManyToManyField(blank=True, related_name='toppings_price', to='orders.PizzaPrice'),
        ),
    ]
