# Generated by Django 2.0.3 on 2019-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190409_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='dinnerplattersprice',
            old_name='DP',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='pizzaprice',
            old_name='pizza_kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='pizzatopping',
            old_name='topping_kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='subsprice',
            old_name='sub',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='subssteakprice',
            old_name='ss',
            new_name='kind',
        ),
        migrations.RemoveField(
            model_name='pizzatopping',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizzatopping',
            name='price',
        ),
    ]
