# Generated by Django 2.0.3 on 2019-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190411_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
