# Generated by Django 2.0.3 on 2019-04-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
