# Generated by Django 2.0.3 on 2019-04-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
