# Generated by Django 3.0.3 on 2020-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='unplaced', max_length=64),
        ),
    ]
